categorical_features:
  job:
    'admin.': 'admin.'
    'blue-collar': 'blue-collar'
    'entrepreneur': 'entrepreneur'
    'housemaid': 'other'
    'management': 'management'
    'retired': 'retired'
    'self-employed': 'other'
    'services': 'services'
    'student': 'student'
    'technician': 'technician'
    'unemployed': 'other'
    'unknown': 'other'

  marital: 
    'married': 'married'
    'single': 'single'
    'divorced': 'divorced'
    'unknown': 'single'

  education:
    'basic.4y': 'basic.4y'
    'high.school': 'high.school'
    'basic.6y': 'basic.6y'
    'basic.9y': 'basic.9y'
    'professional.course': 'professional.course'
    'other': 'other'
    'university.degree': 'university.degree'
    'unknown': 'other'
    'illiterate': 'other'

  housing: 
    'no': 0
    'yes': 1
    'unknown': 0

  loan: 
    'no': 0
    'yes': 1
    'unknown': 0

  y: 
    'yes': 1
    'no': 0

  contact: 
    'telephone': 1
    'cellular': 0
  
cyclical_features:
  months: 
    'jan': 1
    'feb': 2
    'mar': 3
    'apr': 4
    'may': 5
    'jun': 6
    'jul': 7
    'aug': 8
    'sep': 9
    'oct': 10
    'nov': 11
    'dec': 12

  days: 
    'mon': 1
    'tue': 2
    'wed': 3
    'thu': 4
    'fri': 5
    'sat': 6
    'sun': 7

numerical_features:
  'log_duration': 'duration'
  'log_campaign': 'campaign'

selected_features:
  numeric: [
    'age',
    'cons.price.idx',
    'cons.conf.idx',
    'euribor3m',
    'previous',
    'pdays',
    'log_duration',
    'log_campaign',
    'day_of_week1_sin',
    'month1_cos'
    ]
  categorical: [
    'marital',
    'job',
    'education',
    'poutcome'
    ]

model_parameters:
  'n_estimators': 100
  'max_features': 16
  'max_depth': 10